server:
  port: 3000

spring:
  # profiles:
    # active: prod - 이 방법으로 설정하기보다 환경변수 설정하는 것이 좋음

  # 타임리프 설정
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/

  # 파일 업로드 용량 설정 (MultipartFile)
  servlet:
    multipart:
      maxFileSize: 20MB # 파일 하나당 최대 용량
      maxRequestSize: 60MB # 한번에 전송할 수 있는 최대 파일 용량
      fileSizeThreshold: 30MB # 임시 메모리에 저장할 최대 용량, 초과 시 임시 디렉토리에 저장

# 파일 업로드 경로 설정 (환경변수로 설정)
file:
  upload.path: ${file.path}
  upload.url: ${file.url}